server:
  port: 8763
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-node01:8761/eureka,http://eureka-node02:8762/eureka,http://eureka-node03:8763/eureka
spring:
  application:
    name: EurekaServer
